#!/usr/bin/env python3

import os
import sys

from detail.addTestImpl import addTestsImpl


def printHelpMessage():
    print("Usage: addTest <filename>")
    sys.exit()


if len(sys.argv) == 1:
    print("Mising file name")
    printHelpMessage()

if len(sys.argv) > 2:
    print("Too many parameters")
    printHelpMessage()

if sys.argv[1] == "help":
    printHelpMessage()

fileName = sys.argv[1]

if os.path.exists(fileName) is False:
    sys.exit("File '" + fileName + "' does not exist")

addTestsImpl(fileName)
