#!/usr/bin/env python3

# compile and run test

import subprocess
import sys

if len(sys.argv) < 2:
    sys.exit("Missing test name")

testName = sys.argv[1]

cp = subprocess.run(["cmake", "."])
if cp.returncode != 0:
    sys.exit(cp.returncode)

cp = subprocess.run(["cmake", "--build", ".", "--target", testName])
if cp.returncode != 0:
    sys.exit(cp.returncode)

runCommandArgs = ["../bin/" + testName]
if len(sys.argv) == 3:
    runCommandArgs.append("--gtest_filter=" + sys.argv[2] + "*")

cp = subprocess.run(runCommandArgs)
if cp.returncode != 0:
    sys.exit(cp.returncode)
